parameters:
- name: buildConfiguration
  type: string
  default: 'Release'
- name: projectFile
  type: string
- name: displayName
  type: string
  default: 'build-publish'
  

steps:
  - task: DotNetCoreCLI@2
    displayName: '${{parameters.displayName}} ${{ parameters.buildConfiguration }}'
    inputs:
      command: 'build'
      projects: ${{ parameters.projectFile }}
      arguments: '--configuration ${{ parameters.buildConfiguration }}'

- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
