parameters:
- name: WebbAppName
  type: string
- name: buildConfiguration
  type: string
  default: 'Release'

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(Pipeline.Workspace)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(a630b163-559f-468b-bbb3-a9d9f79197b2)'
    appType: 'webApp'
    WebAppName: ${{ parameters.WebbAppName }}
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'
