trigger:
- master
- ft/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: devops/build-publish-template.yml
            parameters:
              projectFile: 'src/SampleProject.API/SampleProject.API.csproj'
              displayName: 'BuildFromTemplate'

  - stage: DeployToTest
    displayName: 'Deploy to test'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployJob
        steps:
          - template: devops/release-template.yml
            parameters:
              WebbAppName: 'webapp-devops24-henrik-test'

  - stage: DeployToProd
    displayName: 'Deploy to prod'
    dependsOn: DeployToTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: DeployToProd
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: devops/release-template.yml
                  parameters:
                    WebbAppName: 'webbapp-devops24-henrik-prod'

