trigger:
- master
- ft/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: 'Build project'
    jobs:
      - job: Build
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: 'src/SampleProject.API/SampleProject.API.csproj'

  - stage: DeployToTest
    displayName: 'Deploy to test'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployJob
        steps:
          - template: devops/release-template.yml
            parameters:
              WebbAppName: 'webapp-devops24-henrik-test'

  - stage: DeployToProd
    displayName: 'Deploy to prod'
    dependsOn: DeployToTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: DeployJob
        steps:
          - template: devops/release-template.yml
            parameters:
              WebbAppName: 'webbapp-devops24-henrik-prod'
