trigger:
  - master
  - ft/*

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
          - template: devops/build-publish-template.yml
            parameters:
              projectFile: 'src/SampleProject.API/SampleProject.API.csproj'
              displayName: 'BuildFromTemplate'

  - stage: DeployToTest
    displayName: 'Deploy to test'
    dependsOn: Build
    condition: succeeded()
    variables:
      environmentName: 'test'
    jobs:
      - job: DeployAndIaCTest
        steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Azure subscription 1(a630b163-559f-468b-bbb3-a9d9f79197b2)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'rg-devops24-ivansson-$(environmentName)'
              location: 'West Europe'
              templateLocation: 'Linked artifact'
              csmFile: 'devops/deploy.bicep'
              csmParametersFile: 'devops/parameters-$(environmentName).bicepparam'
              deploymentMode: 'Incremental'
              deploymentName: 'DevOps24-Test'
              deploymentOutputs: 'bicepOutputs'
              useWithoutJSON: true
          - template: devops/release-template.yml
            parameters:
              WebbAppName: '$(bicepOutputs.appName.Value)'

  - stage: DeployToProd
    displayName: 'Deploy to prod'
    dependsOn: DeployToTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      environmentName: 'prod'
    jobs:
      - job: DeployAndIaCProd
        steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Azure subscription 1(a630b163-559f-468b-bbb3-a9d9f79197b2)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'rg-devops24-ivansson-$(environmentName)'
              location: 'West Europe'
              templateLocation: 'Linked artifact'
              csmFile: 'devops/deploy.bicep'
              csmParametersFile: 'devops/parameters-$(environmentName).bicepparam'
              deploymentMode: 'Incremental'
              deploymentName: 'DevOps24-Prod'
              deploymentOutputs: 'bicepOutputs'
              useWithoutJSON: true

          - template: devops/release-template.yml
            parameters:
              WebbAppName: '$(bicepOutputs.appName.Value)'